### PR TITLE
A few additional changes

### PR DESCRIPTION
**Pull request by ericwclymer**
* Added the ability to choose your own refresh interval instead of defaulting to 1-minute (and changed the default to 5)
* Added a fun konami code easter egg cuz why not
* Added a couple additional shortcuts (rate remove, flag post, reply to post)
* Question mark now opens options page
* Some refactoring

### CODE REVIEW

**Comment by CodyJung** [comment]
LGTM, tho it thinks there's merge conflicts

**Comment by ericwclymer** [comment]
Yeah, sorry that's because I forgot to merge from your fork first. I think I've got it fixed now but I'll double-check

**Comment by ericwclymer** [comment]
Ehh... I changed my mind. Put this on hold for a bit. I'll do more testing.

**Comment by ericwclymer** [comment]
Ok. I think this should all be working now, but that's the stereotypical "I tested my own code" thing to say, so it might be worth a quick test run before you announce/release it.

I added a note in the readme, but I can't find the extension on the chrome extension store anymore. Should it be there?

**Comment by CodyJung** [comment]
Seems good to me! Does this link work for you? It might be unlisted since it doesn't have screenshots: https://chrome.google.com/webstore/detail/ivorytower-checker/lhlkgkbkpkeckoohbbengccfbflpeogf

Also, could you email me the list of usernames and cohort years (if you have them) for recent cohorts? I can also try to figure them out from jdek or Facebook if you don't have it handy.

**Comment by ericwclymer** [comment]
Yeah, that links works for me. 

I do not have anything for the recent cohors. I bet @TravisSpomer would have them if you asked though. Or I can ask him.

**Comment by TravisSpomer** [comment]
Does this help?

https://www.ivorytower.com/Directory.aspx?Show=Email

**Comment by TravisSpomer** [comment]
(If that doesn't work well for you, I can run a quick SQL query and export a table of username-to-cohort or whatever else you'd like. Just let me know, here or on FB Messenger.)

**Pull request merged**
