### PR TITLE
Options page

### PR DESCRIPTION
**Pull request by ericwclymer**
https://github.com/CodyJung/itcheck/issues/3 is addressed by this. 

- It adds an options page
- User can turn off shortcuts
- User can turn on/off the cohort-year-adder
- It starts using chrome sync to sync across devices where the user is signed in

I know I said I was done with the other PR, sorry.

Next step would be customizable shortcuts. I'm also considering adding (small?) images where cohort links are for users.

### CODE REVIEW

**Comment by CodyJung** [comment]
Would you go ahead and increment the version number, then assign this PR to me when you're ok with it?

**Comment by ericwclymer** [comment]
I'm still messing around with this one. I probably shouldn't have created a PR yet. 

I'll make sure to increment it. 

You opposed to me adding my name to the author property?

**Comment by CodyJung** [comment]
Go for it!

**Comment by ericwclymer** [comment]
Ok. I think i'm finally done for a while.

**Comment by ericwclymer** [comment]
I can't figure out how to assign it :-1: sorry

**Comment by CodyJung** [comment]
:+1: I got it! I'll merge it and put together a new upload tomorrow (or later today, I guess it is...)

**Comment by CodyJung** [comment]
:+1: Looks good to me! Seems to work.

**Pull request merged**
